version: "2"

services:
  monitor:
    restart: always
    build: ./monitor
    hostname: am-monitor
    ports:
      - "8000:8000"
    container_name: am-monitor
    command: cd microservice && npm install && node server
    networks:
      - am-net

networks:
  am-net:
