version: "2"

services:
  monitor:
    restart: always
    build: ./monitor
    hostname: am-monitor
    ports:
      - "8000:8000"
    container_name: am-monitor
    command: bash -c 'cd /home/node/microservice && npm install && npm run build && node server'
    networks:
      - am-net

  big-bot:
    restart: always
    build: ./pig_bot
    hostname: big-bot
    ports:
      - "8080:8000"
    container_name: big-bot
    command: bash -c 'cd /home/node/microservice && npm install && npm run build && node server'
    networks:
      - am-net

networks:
  am-net:
